// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface ProviderLoadedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ProviderLoadedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   * @return Whether the broker field is set.
   */
  boolean hasBroker();
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   * @return The broker.
   */
  io.emqx.exhook.BrokerInfo getBroker();
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   */
  io.emqx.exhook.BrokerInfoOrBuilder getBrokerOrBuilder();

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   * @return The meta.
   */
  io.emqx.exhook.RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   */
  io.emqx.exhook.RequestMetaOrBuilder getMetaOrBuilder();
}
